moviefun:
  datasources:
    movies:
      url: jdbc:mysql://localhost:3306/movies?useSSL=false
      username: root
      password:
      maximumPoolSize: 5
    albums:
      url: jdbc:mysql://localhost:3306/albums?useSSL=false
      username: root
      password:
      maximumPoolSize: 6

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

