spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointUrl: http://s3.amazonaws.com
  accessKey: AKIAJKC2LBCNVZX3BP5Q
  secretKey: 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
  bucketName: cf-d725f8b7-0321-4a15-84d5-407491a22fa8
rabbitmq:
  uri: amqp://guest:guest@localhost
  queue: my-rabbit-queue
